times = ('Palmeiras', 'Internacional', 'Fluminense', 'Corinthians', 'Flamengo', 'Athletico-PR', 'Atlético-MG', 'Fortaleza', 'São Paulo', 'América-MG', 'Botafogo', 'Santos', 'Goiás', 'Bragantino', 'Coritiba', 'Cuiabá', 'Ceará SC', 'Atlético-GO', 'Avaí', 'Juventude')
print('-='*35)
print(f' Lista de times do Brasilerão: {times}')
print('-='*35)
print(f' Os 5 primeiros são: {times[:5]}')
print('-='*35)
print(f' Os últimos 4 são: {times[-4:]} ')
print('-='*35)
print(f' Times em ordem Alfabética: {sorted(times)}')
print('-='*35)
print(f" O Fortaleza está na {times.index('Fortaleza')+1}ª colocação")
